# Generated by Django 3.1 on 2023-07-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_contact_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
