# Generated by Django 3.1 on 2023-07-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210313_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount_paid',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(default='useremail@greatkert.com', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='ref',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
